---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: directory
    path: src/app/forestry/data/Content_Pages
    label: Content Pages
    create: documents
    match: '**/*'
    new_doc_ext: json
    templates:
      - content-pages
  - type: directory
    path: src/app/forestry/data
    label: Site Data
    create: all
    match: '**/*.json'
    new_doc_ext: json
upload_dir: public/uploads
public_path: '/uploads'
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: '/srv'
  working_dir: '/srv'
  instant_preview_command: npm run forestry:preview
